// <auto-generated />
namespace NetMud.Authentication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class auth2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(auth2));
        
        string IMigrationMetadata.Id
        {
            get { return "201606230352296_auth2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
