CREATE TABLE [dbo].[Material]
(
    [Id]						BIGINT			IDENTITY (1, 1) NOT NULL,
    [Created]					DATETIME		DEFAULT (getutcdate()) NOT NULL,
    [LastRevised]				DATETIME		DEFAULT (getutcdate()) NOT NULL,
    [Name]						VARCHAR (200)	NOT NULL,
    [Conductive] BIT NOT NULL DEFAULT 0,
    [Magnetic] BIT NOT NULL DEFAULT 0,
    [Flammable] BIT NOT NULL DEFAULT 1,
    [Viscosity] SMALLINT NOT NULL DEFAULT 1,
    [Density] SMALLINT NOT NULL DEFAULT 1,
    [Mallebility] SMALLINT NOT NULL DEFAULT 1,
    [Ductility] SMALLINT NOT NULL DEFAULT 1,
    [Porosity] SMALLINT NOT NULL DEFAULT 1,
    [SolidPoint] SMALLINT NOT NULL DEFAULT 1,
    [GasPoint] SMALLINT NOT NULL DEFAULT 1,
    [TemperatureRetention] SMALLINT NOT NULL DEFAULT 1,
    [Resistance] VARCHAR(MAX) NOT NULL DEFAULT '{}',
    [Composition] VARCHAR(MAX) NOT NULL DEFAULT '{}',
)